# Generated by Django 4.1.4 on 2023-01-14 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import films.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0002_blogpost_author_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='list_of_likers',
            field=models.JSONField(blank=True, default=films.models.default_list_of_likers, null=True, verbose_name='Хто лайкнув'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата додання'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film', verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата додання'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.film', verbose_name='Фільм'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='К-ть лайків'),
        ),
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country', to='films.tag', verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.IntegerField(verbose_name='Тривалість у хв'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='tag1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tag1', to='films.tag', verbose_name='Тег 1'),
        ),
        migrations.AlterField(
            model_name='film',
            name='tag2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tag2', to='films.tag', verbose_name='Тег 2'),
        ),
        migrations.AlterField(
            model_name='film',
            name='text',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='film',
            name='url',
            field=models.URLField(verbose_name='Посилання на трейлер'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Назва тегу'),
        ),
    ]
