# Generated by Django 4.1.4 on 2023-01-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='post_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
