# Generated by Django 4.1.4 on 2023-01-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/post_images'),
        ),
        migrations.AddField(
            model_name='pagepost',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, default='1999-12-31', null=True),
        ),
    ]
