# Generated by Django 4.1.4 on 2023-01-14 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, default='---', null=True, verbose_name='Про себе'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, default='1999-12-31', null=True, verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatars', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post_list',
            field=models.JSONField(blank=True, default=users.models.default_post_list, null=True, verbose_name='Список постів'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(default='---', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='customuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кому належить'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='messages',
            field=models.JSONField(blank=True, default=users.models.default_messages, null=True, verbose_name='Повідомлення'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='Отримувач'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час надсилання'),
        ),
        migrations.AlterField(
            model_name='pagepost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='pagepost',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата додання'),
        ),
        migrations.AlterField(
            model_name='pagepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/post_images', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='pagepost',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='К-ть лайків'),
        ),
        migrations.AlterField(
            model_name='pagepost',
            name='list_of_likers',
            field=models.JSONField(blank=True, default=users.models.default_list_of_likers, null=True, verbose_name='Хто лайкнув'),
        ),
        migrations.AlterField(
            model_name='pagepost',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='pagepost',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Заголовок'),
        ),
    ]
