# Generated by Django 4.1.4 on 2023-01-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_pagepost_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagepost',
            name='list_of_likers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
